- hosts: all
  tasks:
    - name: download tomcat from dlcdn
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.41/bin/apache-tomcat-10.1.41.tar.gz"
        dest: "/root/"

    - name: untar the apache file
      command: tar -zxvf apache-tomcat-10.1.41.tar.gz


    - name: rename the tomcat
      command: mv apache-tomcat-10.1.41 tomcat
      tags: abc

    - name: install java
      command: yum install java-1.8.0-openjdk -y
      
    - name: install java
      command: yum install java-17-amazon-corretto -y
      
    - name: setting the roles in tomcat-user.xml file
      template:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml

    - name: delete two lines in context.xml
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: start the tomcat
      shell: nohup /root/tomcat/bin/startup.sh
